server:
  port: 8301
  session:
    cookie:
      name: UISESSION
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8761/eureka/
  instance:
    hostname: localhost


spring:
  #datasource:
    #url: jdbc:mysql://localhost:3306/notewitch?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    #username: root  
    #password: root
    #driver-class-name: com.mysql.jdbc.Driver
  datasource:
   # driver-class-name:  org.postgresql.Driver
    url: jdbc:postgresql:// + ${HEROKU_POSTGRESQL_MAROO_URL} + /d74oqr268mfr3h?useSSL=true
    username: ${JDBC_DATABASE_USERNAME}  
    password: ${JDBC_DATABASE_PASSWORD}
  application:
    name: db-service
  jpa:
    show-sql: false 
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
       
            
      